export const profile = {
  cardTitle: 'კლიენტის ბარათი',
  nbsTitle: 'საბროკერო ანგარიშის ნომერი',
  nduTitle: 'აქტივების მმართველის N',
  email: 'ელ-ფოსტა',
  phoneNumber: 'ტელეფონის ნომერი',
  privateProfileTitle: 'პერსონალური მონაცემები',
  fullName: 'სახელი',
  birthdayTitle: 'დაბადების თარიღი',
  gender: 'სქესი',
  citizenship: 'მოქალაქეობა',
  placeOfBirth: 'დაბადების ადგილი',
  documentType: 'დოკუმენტის ტიპი',
  passportNumber: 'პასპორტის №',
  passportIssueDate: 'გაცემის თარიღი',
  passportExpiryDate: 'მოქმედების ვადა',
  settingsTitle: 'პროფილის პარამეტრები',
  actionsTitle: 'პროფილის აქტივობები',
  anketaTitle: 'კითხვარი',
  tariffTitle: 'სატარიფო გეგმა',
  modals: {
    settings: {
      title: 'პროფილის პარამეტრები',
      contactInformationTitle: 'საკონტაქტო ინფორმაცია',
      contactInformationSaveBtn: 'ცვლილების დამახსოვრება',
      emailTitle: 'ელ-ფოსტა',
      useForAuthentificationTitle: 'ავტორიზაციისთვის გამოყენება',
      confirmedTitle: 'დადასტურებული',
      emailAddBtn: '+ დამატება',
      phoneTitle: 'ტელ.ნომერი',
      phoneAddBtn: '+ დამატება',
      helpText:
        'გთხოვთ გაითვალისწინოთ: თუ მისამართს შეიცვლით, დაუყოვნებლივ უნდა წარმოადგინოთ დამადასტურებელი დოკუმენტები, წინააღმდეგ შემთხვევაში თქვენს ანგარიშზე ტრანზაქციები დროებით მიუწვდომელი იქნება.',
      addressTitle: 'რეგისტრაციის მისამართი',
      address2Title: 'ფაქტობრივი მისამართი',
      useAsPostTitle: 'შეტყობინებებისთვის გამოყენება',
      confirmAddressText: 'მისამართის დასადასტურებლად,',
      confirmAddressLinkText: 'დოკუმენტები ატვირთეთ აქ',
      countryTitle: 'ქვეყანა',
      cityTitle: 'ქალაქი',
      postCodeTitle: 'ინდექსი',
      addressFormTitle: 'მისამართი',
      profileTitle: 'პროფილი',
      nicknameTitle: 'მომხმარებლის სახელი',
      uploadAvatarTitle: 'ავატარის ატვირთვა',
      loginTitle: 'მომხმარებლის სახელი',
      passwordTitle: 'პაროლი',
      confirmAvatarDeleteTitle: 'წაშლის დადასტურება',
      confirmAvatarDelete: 'ნამდვილად გსურთ ავატარის წაშლა?',
      cancelBtn: 'გაუქმება',
      okBtn: 'დიახ'
    },
    anketa: {
      anketaTitle: 'კითხვარი',
      taxResidenciesTitle: 'საგადასახადო რეზიდენტობა',
      chooseText1: 'აირჩიეთ',
      chooseText2: 'ყველა ქვეყანა,',
      chooseText3: 'სადაც  ხართ საგადასახადო რეზიდენტი.',
      countryTitle: 'ქვეყანა',
      innTitle: 'გადასახადის გადამხდელის კოდი',
      additionalInformationTitle: 'დამატებითი ინფორმაცია',
      beneficiariesTitle: 'მყავს ანგარიშის ბენეფიციარი',
      pepTitle: 'ვარ პოლიტიკურად აქტიური პირი (PEP)',
      residenceTitle: 'ბინადრობის ნებართვა და ანალოგიური დოკუმენტები',
      chooseText4: 'აირჩიეთ ყველა ქვეყანა, სადაც გაქვთ ბინადრობის ნებართვა',
      issuedByTitle: 'გამცემი ორგანო',
      documentNumberTitle: 'დოკუმენტის ნომერი',
      durationTitle: 'ბინადრობის  ვადა',
      noResidenceTitle:
        'არ მაქვს ბინადრობის ნებართვა (ან მისი ეკვივალენტი)  მოქალაქეობის ქვეყნის გარდა.',
      placeOfWorkTitle: 'სამუშაო ადგილი',
      specifyPlaceOfworkTitle: 'მიუთითეთ მიმდინარე სამუშაო ადგილი',
      companyNameTitle: 'კომპანიის დასახელება',
      industryTitle: 'ინდუსტრია',
      jobTitle: 'პოზიცია',
      emailTitle: 'ელ-ფოსტა',
      memberOfNPOTitle: 'ვარ არაკომერციული ორგანიზაციის (NPO) წევრი',
      memberOfNGOTitle: 'ვარ არასამთავრობო ორგანიზაციის (NGO) წევრი',
      selfEmployedStatusTitle: 'ვარ თვითდასაქმებული',
      doNotWorkTitle: 'არ ვმუშაობ',
      addBtn: '+ დამატება',
      bankAccountsTitle: 'საბანკო რეკვიზიტები',
      bankAccountIsMain: 'გამოიყენე როგორც ძირითადი',
      bankNameTitle: 'ბანკის დასახელება',
      isConfirmed: 'დადასტურებული',
      isNotConfirmed: 'დაუდასტურებელი',
      blockBtn: 'დაბლოკვა',
      blockedAccount: 'დაბლოკილი',
      confirmBlockTitle: 'მოქმედების დადასტურება',
      confirmBlockText: 'ნამდვილად გსურთ ანგარიშის დაბლოკვა?',
      okBtn: 'დიახ',
      cancelBtn: 'გაუქმება'
    },
    profileData: {
      title: 'ბენეფიციარის კითხვარი'
    }
  },
  requirements: {
    title: 'ბროკერის  განცხადებები',
    sectionTitle: 'სათაური/სექცია',
    sectionDescription:
      'მოკლე ინსტრუქცია, რომელიც განმარტავს, თუ რა უნდა გაკეთდეს/სად წავიდეთ/რა მოხდება, თუ ამას არ გააკეთებთ',
    addReminderBtn: 'შემახსენე',
    downloadBtn: 'ჩამოტვირთვა',
    reminderCreated: 'შემახსენე',
    inProcess: 'მოთხოვნა მუშავდება'
  }
};
