export const countries = {
  ru: 'Russia',
  au: 'Australia',
  at: 'Austria',
  az: 'Azerbaijan',
  al: 'Albania',
  dz: 'Algeria',
  ao: 'Angola',
  ad: 'Andorra',
  ag: 'Antigua and Barbuda',
  ar: 'Argentina',
  am: 'Armenia',
  af: 'Afghanistan',
  bs: 'Bahamas',
  bd: 'Bangladesh',
  bb: 'Barbados',
  bh: 'Bahrain',
  by: 'Belarus',
  bz: 'Belize',
  be: 'Belgium',
  bj: 'Benin',
  bg: 'Bulgaria',
  bo: 'Bolivia',
  ba: 'Bosnia and Herzegovina',
  bw: 'Botswana',
  br: 'Brazil',
  bn: 'Brunei',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  bt: 'Bhutan',
  vu: 'Vanuatu',
  va: 'Vatican City',
  gb: 'United Kingdom',
  hu: 'Hungary',
  ve: 'Venezuela',
  vn: 'Vietnam',
  ga: 'Gabon',
  ht: 'Haiti',
  gy: 'Guyana',
  gm: 'Gambia',
  gh: 'Ghana',
  gt: 'Guatemala',
  gn: 'Guinea',
  gw: 'Guinea-Bissau',
  de: 'Germany',
  hn: 'Honduras',
  gd: 'Grenada',
  gr: 'Greece',
  ge: 'Georgia',
  dk: 'Denmark',
  dj: 'Djibouti',
  dm: 'Dominica',
  do: 'Dominican Republic',
  eg: 'Egypt',
  zm: 'Zambia',
  zw: 'Zimbabwe',
  il: 'Israel',
  in: 'India',
  id: 'Indonesia',
  jo: 'Jordan',
  iq: 'Iraq',
  ir: 'Iran',
  ie: 'Ireland',
  is: 'Iceland',
  es: 'Spain',
  it: 'Italy',
  ye: 'Yemen',
  cv: 'Cape Verde',
  kz: 'Kazakhstan',
  kh: 'Cambodia',
  cm: 'Cameroon',
  ca: 'Canada',
  qa: 'Qatar',
  ke: 'Kenya',
  cy: 'Cyprus',
  kg: 'Kyrgyzstan',
  cn: 'China',
  co: 'Colombia',
  km: 'Comoros',
  cg: 'Congo',
  cr: 'Costa Rica',
  ci: "Côte d'Ivoire",
  cu: 'Cuba',
  kw: 'Kuwait',
  la: 'Laos',
  lv: 'Latvia',
  ls: 'Lesotho',
  lr: 'Liberia',
  lb: 'Lebanon',
  ly: 'Libya',
  lt: 'Lithuania',
  li: 'Liechtenstein',
  lu: 'Luxembourg',
  mu: 'Mauritius',
  mr: 'Mauritania',
  mg: 'Madagascar',
  mw: 'Malawi',
  my: 'Malaysia',
  ml: 'Mali',
  mv: 'Maldives',
  mt: 'Malta',
  ma: 'Morocco',
  mx: 'Mexico',
  mz: 'Mozambique',
  md: 'Moldova',
  mc: 'Monaco',
  mn: 'Mongolia',
  mm: 'Myanmar',
  na: 'Namibia',
  np: 'Nepal',
  ne: 'Niger',
  ng: 'Nigeria',
  nl: 'Netherlands',
  ni: 'Nicaragua',
  nz: 'New Zealand',
  no: 'Norway',
  ae: 'UAE',
  om: 'Oman',
  pk: 'Pakistan',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  pl: 'Poland',
  pt: 'Portugal',
  rw: 'Rwanda',
  ro: 'Romania',
  sv: 'El Salvador',
  ws: 'Samoa',
  sm: 'San Marino',
  st: 'São Tomé and Príncipe',
  sa: 'Saudi Arabia',
  kp: 'North Korea',
  mk: 'North Macedonia',
  sc: 'Seychelles',
  sn: 'Senegal',
  rs: 'Serbia',
  sg: 'Singapore',
  sy: 'Syria',
  sk: 'Slovakia',
  si: 'Slovenia',
  so: 'Somalia',
  sd: 'Sudan',
  sr: 'Suriname',
  us: 'United States',
  sl: 'Sierra Leone',
  tj: 'Tajikistan',
  th: 'Thailand',
  tz: 'Tanzania',
  tg: 'Togo',
  tt: 'Trinidad and Tobago',
  tn: 'Tunisia',
  tm: 'Turkmenistan',
  tr: 'Turkey',
  ug: 'Uganda',
  uz: 'Uzbekistan',
  ua: 'Ukraine',
  uy: 'Uruguay',
  fj: 'Fiji',
  ph: 'Philippines',
  fi: 'Finland',
  fr: 'France',
  hr: 'Croatia',
  cf: 'Central African Republic',
  td: 'Chad',
  me: 'Montenegro',
  cz: 'Czech Republic',
  cl: 'Chile',
  ch: 'Switzerland',
  se: 'Sweden',
  lk: 'Sri Lanka',
  ec: 'Ecuador',
  er: 'Eritrea',
  sz: 'Eswatini',
  ee: 'Estonia',
  et: 'Ethiopia',
  za: 'South Africa',
  kr: 'South Korea',
  ss: 'South Sudan',
  jm: 'Jamaica',
  jp: 'Japan'
};
