export const profile = {
  cardTitle: 'Карта клиента',
  nbsTitle: 'Номер БС',
  nduTitle: 'Номер счета ДУ',
  email: 'Почта',
  phoneNumber: 'Телефон',
  privateProfileTitle: 'Персональные данные',
  fullName: 'Имя',
  birthdayTitle: 'Дата рождения',
  gender: 'Пол',
  citizenship: 'Гражданство',
  placeOfBirth: 'Место рождения',
  documentType: 'Тип документа',
  passportNumber: '№ паспорта',
  passportIssueDate: 'Дата выдачи',
  passportExpiryDate: 'Конец срока действия',
  settingsTitle: 'Настройки профиля',
  actionsTitle: 'Действия в профиле',
  anketaTitle: 'Анкета',
  tariffTitle: 'Тарифный план'
};
