export const profile = {
  cardTitle: 'Customer account',
  nbsTitle: 'Brokerage account number',
  nduTitle: 'Asset management number',
  email: 'Email',
  phoneNumber: 'Phone number',
  privateProfileTitle: 'Personal data',
  fullName: 'Name',
  birthdayTitle: 'Date of Birth',
  gender: 'Gender',
  citizenship: 'Citizenship',
  placeOfBirth: 'Place of birth',
  documentType: 'Document type',
  passportNumber: 'Passport number',
  passportIssueDate: 'Date of issue',
  passportExpiryDate: 'Validity period',
  settingsTitle: 'Profile settings',
  actionsTitle: 'Profile actions',
  anketaTitle: 'Questionnaire',
  tariffTitle: 'Service tariff plan',
  modals: {
    settings: {
      title: 'Profile settings',
      contactInformationTitle: 'Contact information',
      contactInformationSaveBtn: 'Save changes',
      emailTitle: 'E-mail',
      useForAuthentificationTitle: 'Use for authorization',
      confirmedTitle: 'Confirmed',
      emailAddBtn: '+ Add',
      phoneTitle: 'Phone number',
      phoneAddBtn: '+ Add',
      helpText:
        'Please note: If you change your address, you must immediately provide supporting documents, otherwise transactions on your account will be temporarily unavailable.',
      addressTitle: 'Registration address',
      address2Title: 'Actual address',
      useAsPostTitle: 'Use as mailbox',
      confirmAddressText: 'To confirm this address, you need to',
      confirmAddressLinkText: 'upload documents here',
      countryTitle: 'Country',
      cityTitle: 'City',
      postCodeTitle: 'Postal code',
      addressFormTitle: 'Address',
      profileTitle: 'Profile',
      nicknameTitle: 'Username',
      uploadAvatarTitle: 'Upload an avatar',
      loginTitle: 'Login',
      passwordTitle: 'Password'
    },
    anketa: {
      anketaTitle: 'Questionnaire',
      taxResidenciesTitle: 'Tax residency',
      chooseText1: 'Select',
      chooseText2: 'all countries',
      chooseText3: 'in which you are a tax resident.',
      countryTitle: 'Country',
      innTitle: 'TXID',
      additionalInformationTitle: 'Additional information',
      beneficiariesTitle: 'There are beneficiaries',
      pepTitle: 'I am a PEP (politically exposed person)',
      residenceTitle: 'Residence permit and equivalent documents',
      chooseText4: 'Select all countries where you have a residence permit',
      issuedByTitle: 'Issued by',
      documentNumberTitle: 'Document number',
      durationTitle: 'Duration of stay',
      noResidenceTitle:
        'I do not have a residence permit (or equivalent) in a country other than my citizenship',
      placeOfWorkTitle: 'Place of work',
      specifyPlaceOfworkTitle: 'Please indicate your current place of work',
      companyNameTitle: 'Company name',
      industryTitle: 'Industry',
      jobTitle: 'Job title',
      emailTitle: 'E-mail',
      memberOfNPOTitle: 'I am a member of a non-profit organization (NPO)',
      memberOfNGOTitle: 'I am a member of a non-governmental organization (NGO)',
      selfEmployedStatusTitle: 'Self-employed status',
      doNotWorkTitle: "I don't work",
      addBtn: '+ Add',
      bankAccountsTitle: 'Bank details',
      bankAccountIsMain: 'Use as primary',
      bankNameTitle: 'Name of the bank',
      isConfirmed: 'Confirmed',
      isNotConfirmed: 'Not confirmed',
      blockBtn: 'Block',
      blockedAccount: 'Blocked',
      confirmBlockTitle: 'Confirm action',
      confirmBlockText: 'Do you want to block this account?',
      okBtn: 'ОК',
      cancelBtn: 'Cancel'
    },
    profileData: {
      title: 'Beneficiary Questionnaire'
    }
  },
  requirements: {
    title: 'Broker requirements',
    sectionTitle: 'Title/section of the requirement',
    sectionDescription:
      "A short instruction explaining what needs to be done/provided/where to go/what will happen if you don't do this",
    addReminderBtn: 'Add a reminder',
    downloadBtn: 'Download',
    reminderCreated: 'Reminder created',
    inProcess: 'Request is being processed'
  }
};
