export const topUpAccount = {
  topUpTitle: 'Replenishing a brokerage account',
  currency: 'Currency',
  amount: 'Amount to be credited',
  textCopied: 'Copied',
  accountDetailsDownloadSuccess: 'Bank details downloaded successfully.',
  accountDetailsTitle: 'Rioni Capital bank details',
  accountDetails: 'Bank details for replenishing',
  bank: 'Bank',
  country: 'Country',
  address: 'Address',
  paymentPurposeTitle: 'Payment purpose',
  paymentPurpose: 'Top up a brokerage account RCGEBA1234567890',
  text: 'Please note: When topping up your account using details not specified in your personal account, the top-up process may take longer due to additional verification.',
  sendBtn: 'Send details',
  previewTitle: 'Preview bank details',
  pdfPreview: 'PDF preview',
  downloadPdf: 'Download',
  downloadSuccess: 'Download success.',
  close: 'Close',
  share: 'Share',
  pdfError: 'PDF error',
  downloadTitle: 'Rioni Capital — Bank details for replenishing',
  information: 'Information',
  shareNotSupported: 'Share is not supported',
  date: 'Date'
};
