export interface FlagItem {
  name: string;
  image: string;
  code?: string;
}

export const itemsFlags: FlagItem[] = [
  { name: 'Россия', image: 'ru', code: '7' },
  { name: 'Австралия', image: 'au', code: '61' },
  { name: 'Австрия', image: 'at', code: '43' },
  { name: 'Азербайджан', image: 'az', code: '994' },
  { name: 'Албания', image: 'al', code: '355' },
  { name: 'Алжир', image: 'dz', code: '213' },
  { name: 'Ангола', image: 'ao', code: '244' },
  { name: 'Андорра', image: 'ad', code: '376' },
  { name: 'Антигуа и Барбуда', image: 'ag', code: '1268' },
  { name: 'Аргентина', image: 'ar', code: '54' },
  { name: 'Армения', image: 'am', code: '374' },
  { name: 'Афганистан', image: 'af', code: '93' },
  { name: 'Багамы', image: 'bs', code: '1242' },
  { name: 'Бангладеш', image: 'bd', code: '880' },
  { name: 'Барбадос', image: 'bb', code: '1246' },
  { name: 'Бахрейн', image: 'bh', code: '973' },
  { name: 'Беларусь', image: 'by', code: '375' },
  { name: 'Белиз', image: 'bz', code: '501' },
  { name: 'Бельгия', image: 'be', code: '32' },
  { name: 'Бенин', image: 'bj', code: '229' },
  { name: 'Болгария', image: 'bg', code: '359' },
  { name: 'Боливия', image: 'bo', code: '591' },
  { name: 'Босния и Герцеговина', image: 'ba', code: '387' },
  { name: 'Ботсвана', image: 'bw', code: '267' },
  { name: 'Бразилия', image: 'br', code: '55' },
  { name: 'Бруней', image: 'bn', code: '673' },
  { name: 'Буркина-Фасо', image: 'bf', code: '226' },
  { name: 'Бурунди', image: 'bi', code: '257' },
  { name: 'Бутан', image: 'bt', code: '975' },
  { name: 'Вануату', image: 'vu', code: '678' },
  { name: 'Ватикан', image: 'va', code: '379' },
  { name: 'Великобритания', image: 'gb', code: '44' },
  { name: 'Венгрия', image: 'hu', code: '36' },
  { name: 'Венесуэла', image: 've', code: '58' },
  { name: 'Вьетнам', image: 'vn', code: '84' },
  { name: 'Габон', image: 'ga', code: '241' },
  { name: 'Гаити', image: 'ht', code: '509' },
  { name: 'Гайана', image: 'gy', code: '592' },
  { name: 'Гамбия', image: 'gm', code: '220' },
  { name: 'Гана', image: 'gh', code: '233' },
  { name: 'Гватемала', image: 'gt', code: '502' },
  { name: 'Гвинея', image: 'gn', code: '224' },
  { name: 'Гвинея-Бисау', image: 'gw', code: '245' },
  { name: 'Германия', image: 'de', code: '49' },
  { name: 'Гондурас', image: 'hn', code: '504' },
  { name: 'Гренада', image: 'gd', code: '1473' },
  { name: 'Греция', image: 'gr', code: '30' },
  { name: 'Грузия', image: 'ge', code: '995' },
  { name: 'Дания', image: 'dk', code: '45' },
  { name: 'Джибути', image: 'dj', code: '253' },
  { name: 'Доминика', image: 'dm', code: '1767' },
  { name: 'Доминиканская Республика', image: 'do', code: '1809' },
  { name: 'Египет', image: 'eg', code: '20' },
  { name: 'Замбия', image: 'zm', code: '260' },
  { name: 'Зимбабве', image: 'zw', code: '263' },
  { name: 'Израиль', image: 'il', code: '972' },
  { name: 'Индия', image: 'in', code: '91' },
  { name: 'Индонезия', image: 'id', code: '62' },
  { name: 'Иордания', image: 'jo', code: '962' },
  { name: 'Ирак', image: 'iq', code: '964' },
  { name: 'Иран', image: 'ir', code: '98' },
  { name: 'Ирландия', image: 'ie', code: '353' },
  { name: 'Исландия', image: 'is', code: '354' },
  { name: 'Испания', image: 'es', code: '34' },
  { name: 'Италия', image: 'it', code: '39' },
  { name: 'Йемен', image: 'ye', code: '967' },
  { name: 'Кабо-Верде', image: 'cv', code: '238' },
  { name: 'Казахстан', image: 'kz', code: '7' },
  { name: 'Камбоджа', image: 'kh', code: '855' },
  { name: 'Камерун', image: 'cm', code: '237' },
  { name: 'Канада', image: 'ca', code: '1' },
  { name: 'Катар', image: 'qa', code: '974' },
  { name: 'Кения', image: 'ke', code: '254' },
  { name: 'Кипр', image: 'cy', code: '357' },
  { name: 'Киргизия', image: 'kg', code: '996' },
  { name: 'Китай', image: 'cn', code: '86' },
  { name: 'Колумбия', image: 'co', code: '57' },
  { name: 'Коморы', image: 'km', code: '269' },
  { name: 'Конго', image: 'cg', code: '242' },
  { name: 'Коста-Рика', image: 'cr', code: '506' },
  { name: 'Кот-д\'Ивуар', image: 'ci', code: '225' },
  { name: 'Куба', image: 'cu', code: '53' },
  { name: 'Кувейт', image: 'kw', code: '965' },
  { name: 'Лаос', image: 'la', code: '856' },
  { name: 'Латвия', image: 'lv', code: '371' },
  { name: 'Лесото', image: 'ls', code: '266' },
  { name: 'Либерия', image: 'lr', code: '231' },
  { name: 'Ливан', image: 'lb', code: '961' },
  { name: 'Ливия', image: 'ly', code: '218' },
  { name: 'Литва', image: 'lt', code: '370' },
  { name: 'Лихтенштейн', image: 'li', code: '423' },
  { name: 'Люксембург', image: 'lu', code: '352' },
  { name: 'Маврикий', image: 'mu', code: '230' },
  { name: 'Мавритания', image: 'mr', code: '222' },
  { name: 'Мадагаскар', image: 'mg', code: '261' },
  { name: 'Малави', image: 'mw', code: '265' },
  { name: 'Малайзия', image: 'my', code: '60' },
  { name: 'Мали', image: 'ml', code: '223' },
  { name: 'Мальдивы', image: 'mv', code: '960' },
  { name: 'Мальта', image: 'mt', code: '356' },
  { name: 'Марокко', image: 'ma', code: '212' },
  { name: 'Мексика', image: 'mx', code: '52' },
  { name: 'Мозамбик', image: 'mz', code: '258' },
  { name: 'Молдова', image: 'md', code: '373' },
  { name: 'Монако', image: 'mc', code: '377' },
  { name: 'Монголия', image: 'mn', code: '976' },
  { name: 'Мьянма', image: 'mm', code: '95' },
  { name: 'Намибия', image: 'na', code: '264' },
  { name: 'Непал', image: 'np', code: '977' },
  { name: 'Нигер', image: 'ne', code: '227' },
  { name: 'Нигерия', image: 'ng', code: '234' },
  { name: 'Нидерланды', image: 'nl', code: '31' },
  { name: 'Никарагуа', image: 'ni', code: '505' },
  { name: 'Новая Зеландия', image: 'nz', code: '64' },
  { name: 'Норвегия', image: 'no', code: '47' },
  { name: 'ОАЭ', image: 'ae', code: '971' },
  { name: 'Оман', image: 'om', code: '968' },
  { name: 'Пакистан', image: 'pk', code: '92' },
  { name: 'Панама', image: 'pa', code: '507' },
  { name: 'Папуа - Новая Гвинея', image: 'pg', code: '675' },
  { name: 'Парагвай', image: 'py', code: '595' },
  { name: 'Перу', image: 'pe', code: '51' },
  { name: 'Польша', image: 'pl', code: '48' },
  { name: 'Португалия', image: 'pt', code: '351' },
  { name: 'Руанда', image: 'rw', code: '250' },
  { name: 'Румыния', image: 'ro', code: '40' },
  { name: 'Сальвадор', image: 'sv', code: '503' },
  { name: 'Самоа', image: 'ws', code: '685' },
  { name: 'Сан-Марино', image: 'sm', code: '378' },
  { name: 'Сан-Томе и Принсипи', image: 'st', code: '239' },
  { name: 'Саудовская Аравия', image: 'sa', code: '966' },
  { name: 'Северная Корея', image: 'kp', code: '850' },
  { name: 'Сейшелы', image: 'sc', code: '248' },
  { name: 'Сенегал', image: 'sn', code: '221' },
  { name: 'Сербия', image: 'rs', code: '381' },
  { name: 'Сингапур', image: 'sg', code: '65' },
  { name: 'Сирия', image: 'sy', code: '963' },
  { name: 'Словакия', image: 'sk', code: '421' },
  { name: 'Словения', image: 'si', code: '386' },
  { name: 'Сомали', image: 'so', code: '252' },
  { name: 'Судан', image: 'sd', code: '249' },
  { name: 'Суринам', image: 'sr', code: '597' },
  { name: 'США', image: 'us', code: '1' },
  { name: 'Сьерра-Леоне', image: 'sl', code: '232' },
  { name: 'Таджикистан', image: 'tj', code: '992' },
  { name: 'Таиланд', image: 'th', code: '66' },
  { name: 'Танзания', image: 'tz', code: '255' },
  { name: 'Того', image: 'tg', code: '228' },
  { name: 'Тринидад и Тобаго', image: 'tt', code: '1868' },
  { name: 'Тунис', image: 'tn', code: '216' },
  { name: 'Туркменистан', image: 'tm', code: '993' },
  { name: 'Турция', image: 'tr', code: '90' },
  { name: 'Уганда', image: 'ug', code: '256' },
  { name: 'Узбекистан', image: 'uz', code: '998' },
  { name: 'Украина', image: 'ua', code: '380' },
  { name: 'Уругвай', image: 'uy', code: '598' },
  { name: 'Фиджи', image: 'fj', code: '679' },
  { name: 'Филиппины', image: 'ph', code: '63' },
  { name: 'Финляндия', image: 'fi', code: '358' },
  { name: 'Франция', image: 'fr', code: '33' },
  { name: 'Хорватия', image: 'hr', code: '385' },
  { name: 'Центральноафриканская Республика', image: 'cf', code: '236' },
  { name: 'Чад', image: 'td', code: '235' },
  { name: 'Черногория', image: 'me', code: '382' },
  { name: 'Чехия', image: 'cz', code: '420' },
  { name: 'Чили', image: 'cl', code: '56' },
  { name: 'Швейцария', image: 'ch', code: '41' },
  { name: 'Швеция', image: 'se', code: '46' },
  { name: 'Шри-Ланка', image: 'lk', code: '94' },
  { name: 'Эквадор', image: 'ec', code: '593' },
  { name: 'Эритрея', image: 'er', code: '291' },
  { name: 'Эсватини', image: 'sz', code: '268' },
  { name: 'Эстония', image: 'ee', code: '372' },
  { name: 'Эфиопия', image: 'et', code: '251' },
  { name: 'ЮАР', image: 'za', code: '27' },
  { name: 'Южная Корея', image: 'kr', code: '82' },
  { name: 'Южный Судан', image: 'ss', code: '211' },
  { name: 'Ямайка', image: 'jm', code: '1876' },
  { name: 'Япония', image: 'jp', code: '81' },
  { name: 'Северная Македония', image: 'mk', code: '389' },
];

/**
 * Список стран с кодами телефонов, отсортированный по убыванию длины кода
 * (чтобы более специфичные коды matched first, e.g. 1242 before 1)
 */
export const phoneCountriesSorted = [...itemsFlags]
  .filter(c => c.code)
  .sort((a, b) => (b.code?.length || 0) - (a.code?.length || 0));

export const countries = [
  'Австралия', 'Австрия', 'Азербайджан', 'Албания', 'Алжир', 'Ангола', 'Андорра', 'Антигуа и Барбуда', 'Аргентина', 'Армения', 'Афганистан',
  'Багамы', 'Бангладеш', 'Барбадос', 'Бахрейн', 'Беларусь', 'Белиз', 'Бельгия', 'Бенин', 'Болгария', 'Боливия', 'Босния и Герцеговина', 'Ботсвана', 'Бразилия', 'Бруней', 'Буркина-Фасо', 'Бурунди', 'Бутан',
  'Вануату', 'Ватикан', 'Великобритания', 'Венгрия', 'Венесуэла', 'Вьетнам',
  'Габон', 'Гаити', 'Гайана', 'Гамбия', 'Гана', 'Гватемала', 'Гвинея', 'Гвинея-Бисау', 'Германия', 'Гондурас', 'Гренада', 'Греция', 'Грузия', 'Дания', 'Джибути', 'Доминика', 'Доминиканская Республика',
  'Египет', 'Замбия', 'Зимбабве', 'Израиль', 'Индия', 'Индонезия', 'Иордания', 'Ирак', 'Иран', 'Ирландия', 'Исландия', 'Испания', 'Италия', 'Йемен',
  'Кабо-Верде', 'Казахстан', 'Камбоджа', 'Камерун', 'Канада', 'Катар', 'Кения', 'Кипр', 'Киргизия', 'Китай', 'Колумбия', 'Коморы', 'Конго', 'Корея', 'Косово', 'Коста-Рика', 'Кот-д\'Ивуар', 'Куба', 'Кувейт',
  'Лаос', 'Латвия', 'Лесото', 'Либерия', 'Ливан', 'Ливия', 'Литва', 'Лихтенштейн', 'Люксембург',
  'Маврикий', 'Мавритания', 'Мадагаскар', 'Македония', 'Малави', 'Малайзия', 'Мали', 'Мальдивы', 'Мальта', 'Марокко', 'Мексика', 'Молдова', 'Монако', 'Монголия', 'Мьянма',
  'Намибия', 'Непал', 'Нигер', 'Нигерия', 'Нидерланды', 'Никарагуа', 'Новая Зеландия', 'Норвегия', 'ОАЭ', 'Оман',
  'Пакистан', 'Панама', 'Парагвай', 'Перу', 'Польша', 'Португалия',
  'Руанда', 'Румыния', 'Россия', 'Сальвадор', 'Самоа', 'Сан-Марино', 'Сан-Томе и Принсипи', 'Саудовская Аравия', 'Северная Корея', 'Сейшелы', 'Сенегал', 'Сербия', 'Сингапур', 'Сирия', 'Словакия', 'Словения', 'Сомали', 'Судан', 'Суринам', 'США', 'Сьерра-Леоне',
  'Таджикистан', 'Таиланд', 'Танзания', 'Того', 'Тринидад и Тобаго', 'Тунис', 'Туркменистан', 'Турция', 'Уганда', 'Узбекистан', 'Украина', 'Уругвай',
  'Фиджи', 'Филиппины', 'Финляндия', 'Франция',
  'Хорватия', 'Центральноафриканская Республика', 'Чад', 'Черногория', 'Чехия', 'Чили',
  'Швейцария', 'Швеция', 'Шри-Ланка',
  'Эквадор', 'Эритрея', 'Эсватини', 'Эфиопия', 'Эстония', 'ЮАР', 'Южный Судан', 'Ямайка', 'Япония'
];

export const russianMonths = [
  'янв.',
  'фев.',
  'марта',
  'апр.',
  'мая',
  'июня',
  'июля',
  'авг.',
  'сент.',
  'окт.',
  'нояб.',
  'дек.'
];

export const englishMonths = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sept',
  'Oct',
  'Nov',
  'Dec'
];

export const monthsByLocale: Record<string, string[]> = {
  ru: russianMonths,
  en: englishMonths
};

export const menuItem = [
  {
    name: 'portfolio',
    title: 'header.portfolio'
  },
  // {
  //   name: 'market',
  //   title: 'header.market'
  // },
  {
    name: 'pronouns',
    title: 'header.pronouns'
  },
  {
    name: 'reports',
    title: 'header.reports'
  }
  // {
  //   name: 'analytics',
  //   title: 'header.analytics'
  // }
];