export interface FlagItem {
  name: string;
  image: string;
  code?: string;
}

export const itemsFlags: FlagItem[] = [
  { name: 'ru', image: 'ru', code: '7' },
  { name: 'au', image: 'au', code: '61' },
  { name: 'at', image: 'at', code: '43' },
  { name: 'az', image: 'az', code: '994' },
  { name: 'al', image: 'al', code: '355' },
  { name: 'dz', image: 'dz', code: '213' },
  { name: 'ao', image: 'ao', code: '244' },
  { name: 'ad', image: 'ad', code: '376' },
  { name: 'ag', image: 'ag', code: '1268' },
  { name: 'ar', image: 'ar', code: '54' },
  { name: 'am', image: 'am', code: '374' },
  { name: 'af', image: 'af', code: '93' },
  { name: 'bs', image: 'bs', code: '1242' },
  { name: 'bd', image: 'bd', code: '880' },
  { name: 'bb', image: 'bb', code: '1246' },
  { name: 'bh', image: 'bh', code: '973' },
  { name: 'by', image: 'by', code: '375' },
  { name: 'bz', image: 'bz', code: '501' },
  { name: 'be', image: 'be', code: '32' },
  { name: 'bj', image: 'bj', code: '229' },
  { name: 'bg', image: 'bg', code: '359' },
  { name: 'bo', image: 'bo', code: '591' },
  { name: 'ba', image: 'ba', code: '387' },
  { name: 'bw', image: 'bw', code: '267' },
  { name: 'br', image: 'br', code: '55' },
  { name: 'bn', image: 'bn', code: '673' },
  { name: 'bf', image: 'bf', code: '226' },
  { name: 'bi', image: 'bi', code: '257' },
  { name: 'bt', image: 'bt', code: '975' },
  { name: 'vu', image: 'vu', code: '678' },
  { name: 'va', image: 'va', code: '379' },
  { name: 'gb', image: 'gb', code: '44' },
  { name: 'hu', image: 'hu', code: '36' },
  { name: 've', image: 've', code: '58' },
  { name: 'vn', image: 'vn', code: '84' },
  { name: 'ga', image: 'ga', code: '241' },
  { name: 'ht', image: 'ht', code: '509' },
  { name: 'gy', image: 'gy', code: '592' },
  { name: 'gm', image: 'gm', code: '220' },
  { name: 'gh', image: 'gh', code: '233' },
  { name: 'gt', image: 'gt', code: '502' },
  { name: 'gn', image: 'gn', code: '224' },
  { name: 'gw', image: 'gw', code: '245' },
  { name: 'de', image: 'de', code: '49' },
  { name: 'hn', image: 'hn', code: '504' },
  { name: 'gd', image: 'gd', code: '1473' },
  { name: 'gr', image: 'gr', code: '30' },
  { name: 'ge', image: 'ge', code: '995' },
  { name: 'dk', image: 'dk', code: '45' },
  { name: 'dj', image: 'dj', code: '253' },
  { name: 'dm', image: 'dm', code: '1767' },
  { name: 'do', image: 'do', code: '1809' },
  { name: 'eg', image: 'eg', code: '20' },
  { name: 'zm', image: 'zm', code: '260' },
  { name: 'zw', image: 'zw', code: '263' },
  { name: 'il', image: 'il', code: '972' },
  { name: 'in', image: 'in', code: '91' },
  { name: 'id', image: 'id', code: '62' },
  { name: 'jo', image: 'jo', code: '962' },
  { name: 'iq', image: 'iq', code: '964' },
  { name: 'ir', image: 'ir', code: '98' },
  { name: 'ie', image: 'ie', code: '353' },
  { name: 'is', image: 'is', code: '354' },
  { name: 'es', image: 'es', code: '34' },
  { name: 'it', image: 'it', code: '39' },
  { name: 'ye', image: 'ye', code: '967' },
  { name: 'cv', image: 'cv', code: '238' },
  { name: 'kz', image: 'kz', code: '7' },
  { name: 'kh', image: 'kh', code: '855' },
  { name: 'cm', image: 'cm', code: '237' },
  { name: 'ca', image: 'ca', code: '1' },
  { name: 'qa', image: 'qa', code: '974' },
  { name: 'ke', image: 'ke', code: '254' },
  { name: 'cy', image: 'cy', code: '357' },
  { name: 'kg', image: 'kg', code: '996' },
  { name: 'cn', image: 'cn', code: '86' },
  { name: 'co', image: 'co', code: '57' },
  { name: 'km', image: 'km', code: '269' },
  { name: 'cg', image: 'cg', code: '242' },
  { name: 'cr', image: 'cr', code: '506' },
  { name: 'ci', image: 'ci', code: '225' },
  { name: 'cu', image: 'cu', code: '53' },
  { name: 'kw', image: 'kw', code: '965' },
  { name: 'la', image: 'la', code: '856' },
  { name: 'lv', image: 'lv', code: '371' },
  { name: 'ls', image: 'ls', code: '266' },
  { name: 'lr', image: 'lr', code: '231' },
  { name: 'lb', image: 'lb', code: '961' },
  { name: 'ly', image: 'ly', code: '218' },
  { name: 'lt', image: 'lt', code: '370' },
  { name: 'li', image: 'li', code: '423' },
  { name: 'lu', image: 'lu', code: '352' },
  { name: 'mu', image: 'mu', code: '230' },
  { name: 'mr', image: 'mr', code: '222' },
  { name: 'mg', image: 'mg', code: '261' },
  { name: 'mw', image: 'mw', code: '265' },
  { name: 'my', image: 'my', code: '60' },
  { name: 'ml', image: 'ml', code: '223' },
  { name: 'mv', image: 'mv', code: '960' },
  { name: 'mt', image: 'mt', code: '356' },
  { name: 'ma', image: 'ma', code: '212' },
  { name: 'mx', image: 'mx', code: '52' },
  { name: 'mz', image: 'mz', code: '258' },
  { name: 'md', image: 'md', code: '373' },
  { name: 'mc', image: 'mc', code: '377' },
  { name: 'mn', image: 'mn', code: '976' },
  { name: 'mm', image: 'mm', code: '95' },
  { name: 'na', image: 'na', code: '264' },
  { name: 'np', image: 'np', code: '977' },
  { name: 'ne', image: 'ne', code: '227' },
  { name: 'ng', image: 'ng', code: '234' },
  { name: 'nl', image: 'nl', code: '31' },
  { name: 'ni', image: 'ni', code: '505' },
  { name: 'nz', image: 'nz', code: '64' },
  { name: 'no', image: 'no', code: '47' },
  { name: 'ae', image: 'ae', code: '971' },
  { name: 'om', image: 'om', code: '968' },
  { name: 'pk', image: 'pk', code: '92' },
  { name: 'pa', image: 'pa', code: '507' },
  { name: 'pg', image: 'pg', code: '675' },
  { name: 'py', image: 'py', code: '595' },
  { name: 'pe', image: 'pe', code: '51' },
  { name: 'pl', image: 'pl', code: '48' },
  { name: 'pt', image: 'pt', code: '351' },
  { name: 'rw', image: 'rw', code: '250' },
  { name: 'ro', image: 'ro', code: '40' },
  { name: 'sv', image: 'sv', code: '503' },
  { name: 'ws', image: 'ws', code: '685' },
  { name: 'sm', image: 'sm', code: '378' },
  { name: 'st', image: 'st', code: '239' },
  { name: 'sa', image: 'sa', code: '966' },
  { name: 'kp', image: 'kp', code: '850' },
  { name: 'sc', image: 'sc', code: '248' },
  { name: 'sn', image: 'sn', code: '221' },
  { name: 'rs', image: 'rs', code: '381' },
  { name: 'sg', image: 'sg', code: '65' },
  { name: 'sy', image: 'sy', code: '963' },
  { name: 'sk', image: 'sk', code: '421' },
  { name: 'si', image: 'si', code: '386' },
  { name: 'so', image: 'so', code: '252' },
  { name: 'sd', image: 'sd', code: '249' },
  { name: 'sr', image: 'sr', code: '597' },
  { name: 'us', image: 'us', code: '1' },
  { name: 'sl', image: 'sl', code: '232' },
  { name: 'tj', image: 'tj', code: '992' },
  { name: 'th', image: 'th', code: '66' },
  { name: 'tz', image: 'tz', code: '255' },
  { name: 'tg', image: 'tg', code: '228' },
  { name: 'tt', image: 'tt', code: '1868' },
  { name: 'tn', image: 'tn', code: '216' },
  { name: 'tm', image: 'tm', code: '993' },
  { name: 'tr', image: 'tr', code: '90' },
  { name: 'ug', image: 'ug', code: '256' },
  { name: 'uz', image: 'uz', code: '998' },
  { name: 'ua', image: 'ua', code: '380' },
  { name: 'uy', image: 'uy', code: '598' },
  { name: 'fj', image: 'fj', code: '679' },
  { name: 'ph', image: 'ph', code: '63' },
  { name: 'fi', image: 'fi', code: '358' },
  { name: 'fr', image: 'fr', code: '33' },
  { name: 'hr', image: 'hr', code: '385' },
  { name: 'cf', image: 'cf', code: '236' },
  { name: 'td', image: 'td', code: '235' },
  { name: 'me', image: 'me', code: '382' },
  { name: 'cz', image: 'cz', code: '420' },
  { name: 'cl', image: 'cl', code: '56' },
  { name: 'ch', image: 'ch', code: '41' },
  { name: 'se', image: 'se', code: '46' },
  { name: 'lk', image: 'lk', code: '94' },
  { name: 'ec', image: 'ec', code: '593' },
  { name: 'er', image: 'er', code: '291' },
  { name: 'sz', image: 'sz', code: '268' },
  { name: 'ee', image: 'ee', code: '372' },
  { name: 'et', image: 'et', code: '251' },
  { name: 'za', image: 'za', code: '27' },
  { name: 'kr', image: 'kr', code: '82' },
  { name: 'ss', image: 'ss', code: '211' },
  { name: 'jm', image: 'jm', code: '1876' },
  { name: 'jp', image: 'jp', code: '81' },
  { name: 'mk', image: 'mk', code: '389' }
];

export const phoneCountriesSorted = [...itemsFlags]
  .filter(c => c.code)
  .sort((a, b) => (b.code?.length || 0) - (a.code?.length || 0));

export const countries = itemsFlags.map(flag => flag.name);

export const russianMonths = [
  'янв.',
  'фев.',
  'марта',
  'апр.',
  'мая',
  'июня',
  'июля',
  'авг.',
  'сент.',
  'окт.',
  'нояб.',
  'дек.'
];

export const englishMonths = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sept',
  'Oct',
  'Nov',
  'Dec'
];

export const georgianMonths = [
  'იან',
  'თებ',
  'მარ',
  'აპრ',
  'მაი',
  'ივნ',
  'ივლ',
  'აგვ',
  'სექ',
  'ოქტ',
  'ნოე',
  'დეკ'
];

export const monthsByLocale: Record<string, string[]> = {
  ru: russianMonths,
  en: englishMonths,
  ge: georgianMonths
};

export const menuItem = [
  {
    name: 'portfolio',
    title: 'header.portfolio'
  },
  // {
  //   name: 'market',
  //   title: 'header.market'
  // },
  {
    name: 'pronouns',
    title: 'header.pronouns'
  },
  {
    name: 'reports',
    title: 'header.reports'
  }
  // {
  //   name: 'analytics',
  //   title: 'header.analytics'
  // }
];
